server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobos
    username: postgres
    password: khalid01
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
