server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobos
    username: postgres
    password: khalid01
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-change-this-in-production-use-environment-variable-min-32-chars}
  access-token-expiration: 15
  refresh-token-expiration: 30
